name: ${project.parent.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.craftaro.ultimatestacker.UltimateStacker
softdepend:
  - MythicMobs
  - HolographicDisplays
  - Holograms
  - DecentHolograms
  - CMI
  - WorldGuard
  - EpicSpawners
  - mcMMO
  - WildStacker
  - StackMob
  - BentoBox
  - ViaVersion
loadbefore:
  - WorldGuard

author: Craftaro
website: ${project.parent.url}

commands:
  us:
    description: Reloads the configuration file
    default: true
    aliases:
      - UltimateStacker
    usage: /UltimateStacker reload

permissions:
  UltimateStacker.*:
    description: Inherits all plugin permissions
    children:
      UltimateStacker.admin: true
      UltimateStacker.spawner.silktouch: true
      UltimateStacker.spawner.noSilkDrop: true

  UltimateStacker.admin:
    description: Allows players to edit settings, reload files and other admin commands
    default: op

  UltimateStacker.spawner.silktouch:
    description: Allows the player to pick up spawners using silk touch
    default: op

  UltimateStacker.spawner.noSilkDrop:
    description: Allows the player to receive spawners from mining with a non-silk touched pick
    default: op
